/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package util;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author phat10130059
 */
public class ComboboxUtil {
    
    public static List<String> allCountry(){
        List<String> list = new ArrayList<String>();
        
//        list.add("All");
        list.add("Afghanistan");
        list.add("Åland Islands");
        list.add("Albania");
        list.add("Algeria");
        list.add("American Samoa");
        list.add("Andorra");
        list.add("Angola");
        list.add("Anguilla");
        list.add("Antarctica");
        list.add("Antigua and Barbuda");
        list.add("Argentina");
        list.add("Armenia");
        list.add("Aruba");
        list.add("Australia");
        list.add("Austria");
        list.add("Azerbaijan");
        list.add("Bahamas, The");
        list.add("Bahrain");
        list.add("Bangladesh");
        list.add("Barbados");
        list.add("Belarus");
        list.add("Belgium");
        list.add("Belize");
        list.add("Benin");
        list.add("Bermuda");
        list.add("Bhutan");
        list.add("Bolivia");
        list.add("Bonaire, Sint Eustatius and Saba");
        list.add("Bosnia and Herzegovina");
        list.add("Botswana");
        list.add("Bouvet Island");
        list.add("Brazil");
        list.add("British Indian Ocean Territory");
        list.add("British Virgin Islands");
        list.add("Brunei");
        list.add("Bulgaria");
        list.add("Burkina Faso");
        list.add("Burundi");
        list.add("Cabo Verde");
        list.add("Cambodia");
        list.add("Cameroon");
        list.add("Canada");
        list.add("Cayman Islands");
        list.add("Central African Republic");
        list.add("Chad");
        list.add("Chile");
        list.add("China");
        list.add("Christmas Island");
        list.add("Cocos (Keeling) Islands");
        list.add("Colombia");
        list.add("Comoros");
        list.add("Congo");
        list.add("Congo (DRC)");
        list.add("Cook Islands");
        list.add("Costa Rica");
        list.add("Côte d’Ivoire");
        list.add("Croatia");
        list.add("Cuba");
        list.add("Curaçao");
        list.add("Cyprus");
        list.add("Czech Republic");
        list.add("Denmark");
        list.add("Djibouti");
        list.add("Dominica");
        list.add("Dominican Republic");
        list.add("Ecuador");
        list.add("Egypt");
        list.add("El Salvador");
        list.add("Equatorial Guinea");
        list.add("Eritrea");
        list.add("Estonia");
        list.add("Ethiopia");
        list.add("Falkland Islands");
        list.add("Faroe Islands");
        list.add("Fiji");
        list.add("Finland");
        list.add("France");
        list.add("French Guiana");
        list.add("French Polynesia");
        list.add("French Southern and Antarctic Lands");
        list.add("Gabon");
        list.add("Gambia, The");
        list.add("Georgia");
        list.add("Germany");
        list.add("Ghana");
        list.add("Gibraltar");
        list.add("Greece");
        list.add("Greenland");
        list.add("Grenada");
        list.add("Guadeloupe");
        list.add("Guam");
        list.add("Guatemala");
        list.add("Guernsey");
        list.add("Guinea");
        list.add("Guinea-Bissau");
        list.add("Guyana");
        list.add("Haiti");
        list.add("Heard Island and McDonald Islands");
        list.add("Holy See (Vatican City)");
        list.add("Honduras");
        list.add("Hong Kong SAR");
        list.add("Hungary");
        list.add("Iceland");
        list.add("India");
        list.add("Indonesia");
        list.add("Iran");
        list.add("Iraq");
        list.add("Ireland, Republic of");
        list.add("Isle of Man");
        list.add("Israel");
        list.add("Italy");
        list.add("Jamaica");
        list.add("Japan");
        list.add("Jersey");
        list.add("Jordan");
        list.add("Kazakhstan");
        list.add("Kenya");
        list.add("Kiribati");
        list.add("Korea");
        list.add("Kuwait");
        list.add("Kyrgyzstan");
        list.add("Laos");
        list.add("Latvia");
        list.add("Lebanon");
        list.add("Lesotho");
        list.add("Liberia");
        list.add("Libya");
        list.add("Liechtenstein");
        list.add("Lithuania");
        list.add("Luxembourg");
        list.add("Macao SAR");
        list.add("Macedonia, FYRO");
        list.add("Madagascar");
        list.add("Malawi");
        list.add("Malaysia");
        list.add("Maldives");
        list.add("Mali");
        list.add("Malta");
        list.add("Marshall Islands");
        list.add("Martinique");
        list.add("Mauritania");
        list.add("Mauritius");
        list.add("Mayotte");
        list.add("Mexico");
        list.add("Micronesia");
        list.add("Moldova");
        list.add("Monaco");
        list.add("Mongolia");
        list.add("Montenegro");
        list.add("Montserrat");
        list.add("Morocco");
        list.add("Mozambique");
        list.add("Myanmar");
        list.add("Namibia");
        list.add("Nauru");
        list.add("Nepal");
        list.add("Netherlands");
        list.add("New Caledonia");
        list.add("New Zealand");
        list.add("Nicaragua");
        list.add("Niger");
        list.add("Nigeria");
        list.add("Niue");
        list.add("Norfolk Island");
        list.add("Northern Mariana Islands");
        list.add("North Korea");
        list.add("Norway");
        list.add("Oman");
        list.add("Pakistan");
        list.add("Palau");
        list.add("Palestinian Authority");
        list.add("Panama");
        list.add("Papua New Guinea");
        list.add("Paraguay");
        list.add("Peru");
        list.add("Philippines");
        list.add("Pitcairn Islands");
        list.add("Poland");
        list.add("Portugal");
        list.add("Puerto Rico");
        list.add("Qatar");
        list.add("Reunion");
        list.add("Romania");
        list.add("Russia");
        list.add("Rwanda");
        list.add("Saint Barthélemy");
        list.add("Saint Kitts and Nevis");
        list.add("Saint Lucia");
        list.add("Saint Martin");
        list.add("Saint Pierre and Miquelon");
        list.add("Saint Vincent and the Grenadines");
        list.add("Samoa");
        list.add("San Marino");
        list.add("São Tomé and Príncipe");
        list.add("Saudi Arabia");
        list.add("Senegal");
        list.add("Serbia");
        list.add("Seychelles");
        list.add("Sierra Leone");
        list.add("Singapore");
        list.add("Sint Maarten");
        list.add("Slovakia");
        list.add("Slovenia");
        list.add("Solomon Islands");
        list.add("Somalia");
        list.add("South Africa");
        list.add("South Georgia and the South Sandwich Islands");
        list.add("South Sudan");
        list.add("Spain");
        list.add("Sri Lanka");
        list.add("St Helena, Ascension, Tristan da Cunha");
        list.add("Sudan");
        list.add("Suriname");
        list.add("Svalbard and Jan Mayen");
        list.add("Swaziland");
        list.add("Sweden");
        list.add("Switzerland");
        list.add("Syria");
        list.add("Taiwan");
        list.add("Tajikistan");
        list.add("Tanzania");
        list.add("Thailand");
        list.add("Timor-Leste");
        list.add("Togo");
        list.add("Tokelau");
        list.add("Tonga");
        list.add("Trinidad and Tobago");
        list.add("Tunisia");
        list.add("Turkey");
        list.add("Turkmenistan");
        list.add("Turks and Caicos Islands");
        list.add("Tuvalu");
        list.add("Uganda");
        list.add("Ukraine");
        list.add("United Arab Emirates");
        list.add("United Kingdom");
        list.add("United States");
        list.add("Uruguay");
        list.add("US Minor Outlying Islands");
        list.add("US Virgin Islands");
        list.add("Uzbekistan");
        list.add("Vanuatu");
        list.add("Venezuela");
        list.add("Vietnam");
        list.add("Wallis and Futuna");
        list.add("Yemen");
        list.add("Zambia");
        list.add("Zimbabwe");

        return list;
    }
    
}
